Create ignore-2.16.txt
Fix the following sanity error caused by the new usage of Ansible 2.16 as the "devel" sanity version.

------------------------------
ERROR: plugins/action/sonic.py:0:0: action plugin has no matching module to provide documentation